### ISSUE TITLE
$extensionStatus->getFIK() == NULL

### ISSUE THREAD

**Issue by lamvanduyet** [ondrakoupil/csob#10]
Hi,
getFik() after successfull payments returns null..I don't know what is wrong. All I do after redirect is: $extensionStatus = new EETStatusExtension();
echo $extensionStatus->getFIK();
Do I miss something?
Thank you for help.

**Comment by ondrakoupil** [comment]
Hi,
the Extension object is meant to be used together with main Client methods, `paymentStatus()` in your case. You'll need the payment's PayID - that's the code you receive from `$client->receiveReturningCustomer()`, you should save it for future use.
To get payment status together with the status of EET transaction:

```php
$extension = new EETStatusExtension();
$paymentStatus = $client->paymentStatus($payId, true, $extension);
$eetStatus = $extension->getEETStatus();
$fik = $extension->getFIK();
```
