### ISSUE TITLE
Matoucí exception hláška

### ISSUE THREAD

**Issue by DanielNoga** [ondrakoupil/csob#12]
Postup:
* V bráně mít nastavené hlídání duplikátních požadavků
* Vytvořit nový požadavek a provést platbu
* Znovu vytvořit nový požadavek, ale se stejným číslem, jako předchozí
* Brána vrátí chybový kód značící duplicitní platbu
* Knihovna zahlásí OndraKoupil\Csob\Exception: Result signature is incorrect. Please make sure that bank's public key in file specified in config is correct and up-to-date. 

-> Hláška signalizuje jiný problém, než o který se ve skutečnosti jedná.

**Comment by DanielNoga** [comment]
Nejsem si úplně jistý, ale mám pocit, že ve verzi 1.5 fungovalo správně a rozbilo se až s novou 1.7 (aktuálně mám 1.7.2)

**Comment by ondrakoupil** [comment]
Tahle exception znamená, že selhalo ověření podpisu u odpovědi z banky. Můžete poslat trace log s podrobnostmi dané komunikace? Buď sem do issue, nebo e-mailem na ondrakoupil@gmail.com, pokud obsahuje nějaké neveřejné údaje.
Viz https://github.com/ondrakoupil/csob#logování

**Comment by DanielNoga** [comment]
Nasimuloval jsem na testovací platební bráně:
[csob.txt](https://github.com/ondrakoupil/csob/files/1102642/csob.txt)

Kód se mezi požadavky nezměnil. Jen jsem provedl operaci dvakrát za sebou se stejným číslem.

**Comment by DanielNoga** [comment]
Když si debuguji, tak ČSOB posílá reálně tuto odpověď:
```
{
"dttm":"--nějakéDttm--",
"signature":"--nějakáSignature--",
"payId":"5b2bf4538e0e1CF",
"resultCode":110,
"resultMessage":"Invalid paymentInit request: authorized trx for merchantId M1MIPS0662 and orderNo 1000002 already exists"
}
```

**Comment by ondrakoupil** [comment]
Díky, už vyřešeno. ČSOB v takovém případě neposílá paymentStatus, takže podpis opravdu nevychází. V v1.7.4 to je ošetřené.
