### ISSUE TITLE
Nefunguje logoVersion a colorSchemeVersion

### ISSUE THREAD

**Issue by DanielNoga** [ondrakoupil/csob#13]
Vytvořil jsem `new Payment();` a nastavil jsem $colorSchemeVersion a $logoVersion. Vypadá to, ale že to nemá vliv na bránu. Podle kódu si nejsem jistý, zda se zakomentované proměnné jen ignorují pro výpočet signature, nebo jestli se kvůli tomu i rozbije jejich posílání na API brány

```
private $fieldsInOrder = array(
		"merchantId",
		"orderNo",
		"dttm",
		"payOperation",
		"payMethod",
		"totalAmount",
		"currency",
		"closePayment",
		"returnUrl",
		"returnMethod",
		"cart",
		"description",
		"merchantData",
		"customerId",
		"language",
		"ttlSec",
		//"logoVersion",
		//"colorSchemeVersion"
	);
```

**Comment by ondrakoupil** [comment]
Můžete prosím poslat výstup z debug logu? Viz https://github.com/ondrakoupil/csob#logování
Dík

**Comment by DanielNoga** [comment]
Verze 1.7.4, obsah Payment 

```
OndraKoupil\Csob\Payment::__set_state(array(
   'merchantId' => NULL,
   'orderNo' => '1700012',
   'totalAmount' => 0,
   'currency' => NULL,
   'closePayment' => NULL,
   'returnUrl' => NULL,
   'returnMethod' => NULL,
   'cart' => 
  array (
  ),
   'description' => NULL,
   'merchantData' => NULL,
   'customerId' => NULL,
   'language' => NULL,
   'dttm' => NULL,
   'payOperation' => NULL,
   'payMethod' => NULL,
   'foreignId' => NULL,
   'ttlSec' => NULL,
   'logoVersion' => 10,
   'colorSchemeVersion' => NULL,
   'fieldsInOrder' => 
  array (
    0 => 'merchantId',
    1 => 'orderNo',
    2 => 'dttm',
    3 => 'payOperation',
    4 => 'payMethod',
    5 => 'totalAmount',
    6 => 'currency',
    7 => 'closePayment',
    8 => 'returnUrl',
    9 => 'returnMethod',
    10 => 'cart',
    11 => 'description',
    12 => 'merchantData',
    13 => 'customerId',
    14 => 'language',
    15 => 'ttlSec',
  ),
))
```

přiložené logy z testovací brány: 
[csob_log.txt](https://github.com/ondrakoupil/csob/files/1281370/csob_log.txt)
[csob_tracelog.txt](https://github.com/ondrakoupil/csob/files/1281369/csob_tracelog.txt)

**Comment by ondrakoupil** [comment]
Díky. Koukám na to, v době kdy jsem tuto verzi vyvíjel, tak to z nějakého důvodu nefungovalo a brána požadavky s logoVersion nebo colorSchemeVersion odmítala kvůli podpisu, nyní to už nedělá problémy. Zkuste prosím nejnovější verzi v masteru f15c9cc (případně si jen patchněte src/Payment.php), jestli to bude fungovat.

**Comment by DanielNoga** [comment]
S novou verzí funguje brána pouze pokud jsou vyplněné colorSchemeVersion a logoVersion . Pokud je alespoň jedna z nich nenastavená, skončí to chybou.

[csob_log.txt](https://github.com/ondrakoupil/csob/files/1296476/csob_log.txt)
[csob_tracelog.txt](https://github.com/ondrakoupil/csob/files/1296475/csob_tracelog.txt)

**Comment by ondrakoupil** [comment]
Zkuste prosím ještě novou verzi 245b6b2, už by to mělo projít ve všech případech...

**Comment by DanielNoga** [comment]
Díky, funguje!
