### ISSUE TITLE
Invalid format of cart/description, begins/ends with whitespace

### ISSUE THREAD

**Issue by jaygridley** [ondrakoupil/csob#14]
Hi,

there could be issue with payment's cart description which results in gateway error with code 100, saying "Invalid format of cart/description, begins/ends with whitespace". This could happen, when you try to send cart item's description longer then 40 characters. Your library correctly truncates this description to 40 characters, but truncation should be followed by trimming white spaces. 

For example cart item's description 'Subscription of ABC Company spol. s. r. o.' will be truncated to 'Subscription of ABC ,Company spol. s. r. ' which ends with space.

I am afraid, that official docs for API does not mention this. Hope this helps.

**Comment by ondrakoupil** [comment]
Hi,
please can you check this is really happening? The description and name are trimmed in current version:
https://github.com/ondrakoupil/csob/blob/master/src/Payment.php#L269
This issue was already discussed in #9 and was fixed in version 1.7.3. Are you using the latest version?
Thanks.

**Comment by jaygridley** [comment]
Hi,
I was not. It's really fixed in 1.7.3. Closing this one. Sorry for the inconvenience.
