### ISSUE TITLE
Malformed UTF8 character causes API returned HTTP code 400, which is not code 200. Probably wrong signature, check crypto keys.

### ISSUE THREAD

**Issue by pavkriz** [ondrakoupil/csob#17]
Malformed UTF8 character in cart's item name causes "API returned HTTP code 400, which is not code 200. Probably wrong signature, check crypto keys." exception.

Root cause: json_encode returns enpty string when serializing structure having malformed UTF8 character. One should check json_last_error() before send the request.

**Comment by janbarasek** [comment]
Do you use bank public key?

**Comment by pavkriz** [comment]
https://github.com/ondrakoupil/csob/blob/043a42ddca1366115c93303174aeaab8bb51ec9e/src/Client.php#L1409

json_last_error() should be checked before sending the request.

**Comment by ondrakoupil** [comment]
I'll look into it.

**Comment by ondrakoupil** [comment]
Should be fixed in https://github.com/ondrakoupil/csob/commit/1efb755b8fd081c3cec53be613c6988326986f6f, please can you verify it is OK now?
