### ISSUE TITLE
Support for payment/checkout

### ISSUE THREAD

**Issue by rootpd** [ondrakoupil/csob#19]
Hi,

I wanted to implement `payment/checkout` call which is not supported by your library. It's not documented publicly and is an opt-in feature that needs to be approved by the bank. It's displaying payment window in iframe in very compact form - as you can for example see on Alza.cz eshop.

You might have not implemented it on purpose, so before trying to make a PR: are you open to have an publicly undocumented feature in the library?

![image](https://user-images.githubusercontent.com/812909/49079548-23aaeb00-f241-11e8-8b0f-cd6052ce67f2.png)

Thanks.

**Comment by ondrakoupil** [comment]
Hi,
sure, create a PR.
Thanks.

**Comment by ondrakoupil** [comment]
Merged. Thanks.
