### ISSUE TITLE
Currency

### ISSUE THREAD

**Issue by littlewall** [ondrakoupil/csob#2]
Dobrý den,
mohl byste mi prosím poradit, jak se dá u nové platby nastavit měna/currency? eAPI v1.5 od 10.1.2016 požaduje měnu zadat u opakovaných plateb, a skript mi tak hází chybu "API returned an error: resultCode "110", resultMessage: If 'totalAmount' is set then 'currency' parameter must be set too".

Děkuji předem za jakoukoliv nápovědu.

Milan Zítka

**Comment by ondrakoupil** [comment]
Dobrý den,
currency by měla být "CZK" jako default, i když ji sám nenastavíte. Můžete postnout (nebo poslat na mail koupil@optimato.cz) log komunikace? Získáte ho ze souboru nastavitelného pomocí $client->setLog(...) a $client->setTraceLog(...).

**Comment by littlewall** [comment]
Děkuji za reakci. Vím, že je měna defaultně nastavena, také do minulého týdne vše fungovalo (zatím bránu pouze testuji). "Aktivační platba" proběhne v pořádku, chyba nastane až u opakované platby.

[log.txt](https://github.com/ondrakoupil/csob/files/87852/log.txt)
[tracelog.txt](https://github.com/ondrakoupil/csob/files/87851/tracelog.txt)

U platební brány ČSOB píšou o této změně: [10.1.2016] doplněn popis parametrů totalAmount a currency u operace payment/recurrent, u parametru currency opraven datový typ

**Comment by ondrakoupil** [comment]
Díky za upozornění, nutnost specifikovat $currency je na bráně nová, dříve to opravdu fungovalo i bez toho. Stáhněte si verzi 1.5.2, tam je již situace ošetřená. Případně můžete specifikovat $newPayment->currency při volání metody paymentRecurrent().

**Comment by littlewall** [comment]
Děkuji mockrát za opravu. Aktualizováno a vše funguje.
