### ISSUE TITLE
Unwanted decimals in totalAmount after json_encoding request payload

### ISSUE THREAD

**Issue by rootpd** [ondrakoupil/csob#21]
I've encountered an error when trying to charge a specific amount.

My cart has a calculated total amount of `13064` (130.64CZK) and the `$payload` variable of `\OndraKoupil\Csob\Client` respects that.

However when the payload is encoded via `json_encode` (https://github.com/ondrakoupil/csob/blob/master/src/Client.php#L1467), the `totalAmount` gets casted to `"totalAmount":13063.999999999998`  which is not something that the bank accepts and I get back 400 Bad Request response because of that.

I've tried to configure `serialize_precision` (http://php.net/manual/en/ini.core.php#ini.precision) and also use `JSON_PRESERVE_ZERO_FRACTION` encode option, but with no luck yet.

Tested on PHP 7.2.

**Comment by ondrakoupil** [comment]
Hi, I can't make this bug appear in my environment. It might be something related to specific PHP version or configuration on your machine. I tried a simple fix by rounding and intval-ing the price. Please can you try if 15973e7 fixes the problem?

**Comment by rootpd** [comment]
Suprisingly, this really helped. I'm starting to understand why. The price I generated was a result of a division calculation and that floating point representation could just get a very little bit off.

What I did was I made a calculation, rounded it to two decimals and when generating the cart I multiplied it by 100. Internally the PHP still represented the value as float which caused the issue after JSON encoding the payload.

Now I'm thinking whether you shouldn't revert this last change. It feels that rounding and providing intval should be responsibility of the caller and the library should just enforce it. What do you think?

**Comment by ondrakoupil** [comment]
Well, from academic point of view I agree. But from the practical point of view I find this change quite useful and purposeful. I think there is no real reason for not rounding the price, and it can prevent some unwanted mistakes and save someone from running into the same trap as you did. The purpose of the library is to make usage of bank's API easier, safer and that the developer doesn't need to know all the nuances of the API...

**Comment by rootpd** [comment]
Fair point. It really is useful and unless someone actually complains that it makes their life harder, it makes sense to keep it.

**Comment by ondrakoupil** [comment]
Okey, I agree. I'll include it in next release.
