### ISSUE TITLE
Documentation: English

### ISSUE THREAD

**Issue by khikmatullaev** [ondrakoupil/csob#23]
Thank you a lot for your extension. 
I would you to suggest you extend the documentation by adding the English language. Since the majority of the documentation for extensions are in English. What do you think about it?

**Comment by ondrakoupil** [comment]
Hi Akmal,
you can find documentation in English here: https://github.com/ondrakoupil/csob/blob/master/README.en.md

Good point is that there isn't a link to the english file from default readme.md, so english users might not notice there is an english version. I will add it there.
