### ISSUE TITLE
Attempt to use oneClickInit fails due to missing required parameter

### ISSUE THREAD

**Issue by rootpd** [ondrakoupil/csob#26]
Hi,

during testing of v1.8 we've found an issue when attempting to charge oneClick payment. The bank API responds with following body:

```json5
{
    "dttm": "20200212160057",
    "signature": "*REDACTED*",
    "payId": "*REDACTED*",
    "resultCode": 100,
    "resultMessage": "Missing parameter clientIp",
    "paymentStatus": 6
}
```

As this wasn't an issue before, we've checked why is this happening. 

- In [v1.8](https://github.com/csob/paymentgateway/wiki/Metody-pro-OneClick#oneclick-init-operation) of API, `clientIp` parameter is mandatory. It's a bit counter-intuitive as you might do an offline charge, but seems like they don't care and require some IP address.
- In [v1.7](https://github.com/csob/paymentgateway/wiki/eAPI-1.7#post-httpsapiplatebnibranacsobczapiv17paymentoneclickinit-) this field was not event present.

Currently I don't see a way how to tell the library to include `clientIp` to the payload of `oneClickInit` request. Will you be able to look at it?

Thanks!

**Comment by ondrakoupil** [comment]
Sure, I will look into it a.s.a.p.

**Comment by rootpd** [comment]
Thanks. In the meantime I'm trying to figure out why it's even there. Doesn't really make sense for offline (recurring) payments. https://github.com/csob/paymentgateway/issues/471

**Comment by ondrakoupil** [comment]
Please try again with 545eb8ab236ff3d9d10b35cf57e6e01c4086b11c, will it work? 
I added the clientIp parameter in oneclick/init method and also removed description and added merchantData parameters (which were also removed/added in API 1.8).
Also I added paymentOneClickEcho method for calling oneclick/echo, which has somehow eluded me.

**Comment by rootpd** [comment]
Looks good, payment got through correctly on the sandbox gateway. Seems that `clientIp` is just for logging purposes as `127.0.0.1` went through just fine.

**Comment by ondrakoupil** [comment]
Thanks. Can you test it in production environment in near future so that we can be sure it really works OK? I'd tag it with new version then.

**Comment by rootpd** [comment]
Deployed to production, it's working.

**Comment by ondrakoupil** [comment]
Thanks, closing.
