### ISSUE TITLE
csob-client.php kontra Client.php

### ISSUE THREAD

**Issue by maggi1** [ondrakoupil/csob#27]
Ahoj Ondro, to co jsi naprogramoval je velká věc. Já už jsem nějaké brány implementoval (GoPay, GP WebPay), ale je to již dávno. Zkouším nyní implementovat bránu ČSOB, tak nějak kolem toho kroužím a stále nevím jak do toho. Líbilo by se mi tvoje řešení, ale z jedné věci jsem trochu jelen. Ve složce dist je soubor csob-client.php, který je alespoň na začátku stejný jako Client.php. Něco mi říká, že mi stačí pracovat s csob-client.php. Je to tak? No a pak je tu taky test spojení s bránou - kam se ty kódy jako vloží?
try {
	$client->testGetConnection();
	$client->testPostConnection();

} catch (Exception $e) {
	echo "Something went wrong: " . $e->getMessage();
}

Přdem ti děkuju za odpověď, zdraví Milan

**Comment by ondrakoupil** [comment]
Ahoj Milane,

`dist/csob-client.php` použij, pokud v projektu nepoužíváš nástroj Composer. V tomto souboru jsou všechny potřebné třídy pohromadě a stačí tedy jen includovat tento jediný soubor. Při použití Composeru anebo jakéhokoliv PSR-4 kompatibilního class loaderu není potřeba nic nikam includovat a třídy se budou načítat přímo z adresáře `src`.

Test spojení s bránou - `testGetConnection()` a `testPostConnection()` jsou jen pomocné nástroje pro ověření, že jsou správně nastavené klíče, podepisování, Merchant ID a všechny podobné náležitosti v třídě Config. Můžeš je použít v nějakém pomocném skriptu, který jednou spustíš někde bokem, anebo to nemusíš používat vůbec. V ostrém provozu je potřebovat nebudeš.

**Comment by maggi1** [comment]
Klíče jsem otestoval v testovacím prostředí banky a fungovalo to. Přesto:
Fatal error: Uncaught OndraKoupil\Csob\Exception: Result signature is incorrect. Please make sure that bank's public key in file specified in config is correct and up-to-date. in /www/doc/www.easyweb4u.cz/www/ibcn-sale/csob-client.php:1564 Stack trace: #0 /www/doc/www.easyweb4u.cz/www/ibcn-sale/csob-client.php(177): OndraKoupil\Csob\Client->sendRequest('payment/init', Array, 'POST', Array, NULL, false, false, Array) #1 /www/doc/www.easyweb4u.cz/www/ibcn-sale/csob-client.php(34): OndraKoupil\Csob\Client->paymentInit(Object(OndraKoupil\Csob\Payment)) #2 {main} thrown in /www/doc/www.easyweb4u.cz/www/ibcn-sale/csob-client.php on line 1564

Neměla by se někde nastavit URL brány (testovací)? Není toto potřeba změnit: GatewayUrl::TEST_LATEST

**Comment by ondrakoupil** [comment]
Je potřeba použít veřejný klíč banky a privátní klíč svůj. Ne svůj veřejný klíč.
URL API se nastavuje v třídě Config - podle toho pak knihovna komunikuje s testovací nebo s ostrou verzí bankovného API. Viz https://github.com/ondrakoupil/csob#nastaven%C3%AD

**Comment by maggi1** [comment]
Ondro, já vím, mám tam veřejný testovací klíč banky mips_iplatebnibrana.csob.cz.pub, a tyto použité klíče (+ privátní testovací) mi fungují v testovacím prostředí ČSOB. Tady to hází chybu. Ten TEST_LATEST je asi ok, dole v kódu to odkazuje na testovací bránu 1.8

**Comment by jprkna** [comment]
Dotaz na podobné téma. Již nějaký ten pátek využívám soubor csob-client.php
Bohužel nevím jakou verzi mám ... Jak to prosím zjistím?
A druhý dotaz, pokud přepíšu soubor csob-client.php nejnovějším souborem bude vše fungovat? Je možné že by něco bylo zpětně nekompatibilní?

**Comment by ondrakoupil** [comment]
Právě proto je dobré použít raději Composer :-)

Pokud už máte jenom soubor csob-client.php a ne celý balíček stažený z Githubu, nejlepší bude v csob-client.php najít třídu GatewayUrl a v ní konstantu PRODUCTION_LATEST - z ní zjistíte, jestli je to knihovna z doby API 1.7, 1.8 nebo jakého ještě staršího.

Zpětná nekompatibilita není ani tak v knihovně, jako hlavně v bankovním API. Pokud přejdete z API 1.7 na 1.8, tak tam nějaké změny jsou (jsou popsané v readme zde na githubu). Upgradujete-li pak csob-client.php, bude záležet na tom, jaký Config používáte a zda v něm máte $url nastavenou na konstantu PRODUCTION_LATEST nebo na konkrétní verzi API. Pokud latest, tak knihovna volá nejnovější dostupné API a tímpádem upgradem csob-client.php se i upgraduje API (protože se změnila konstanta latest) a bude potřeba zkontrolovat, zda vám vše funguje. Případně v Configu nastavit nějakou konkrétní verzi bankovního API.

**Comment by jprkna** [comment]
Děkuji rozumím. Další projekt mám již řešený Composerem.
