### ISSUE TITLE
$foreignId vs $payId

### ISSUE THREAD

**Issue by burrak** [ondrakoupil/csob#31]
metoda `function signAndExport(Client $client)` neproběhne správně ve chvíli, kdy potřebuji instanci Payment znovu použít (klasicky applepay/init -> applepay/start), protože se ve třídě Payment používá pro payId (které vrací banka) property $foreignId, a není zde nikde párování, tudíž vznikne nevalidní payload, a applepay/start neproběhne, resp. to vyhodí notice `Notice: Undefined property: OndraKoupil\Csob\Payment::$payId`

**Comment by ondrakoupil** [comment]
Instance Payment se používá jen pro payment/init, nikde jinde. Ostatní metody, třeba ty applepay/init a applepay/start, už pracují přímo pouze s payId jako samostatný string parametr. Payment by se do nich vůbec používat neměl... Tedy alespoň podle toho, jak tomu rozumím.
https://github.com/csob/paymentgateway/wiki/Metody-pro-Apple-Pay#metoda-applepayinit-
https://github.com/csob/paymentgateway/wiki/Metody-pro-Apple-Pay#metoda-applepaystart-

**Comment by burrak** [comment]
Jo takhle... Já že např. `function paymentOneClickStart(Payment $newPayment, $extensions = array())` přijímá Payment v parametru. My používáme nějakou starší verzi, kde se payload sestavuje přes `setFieldsInOrder($array)`, a ve chvíli, kdy se tam právě $payId jmenuje $foreignId, tak to nefunguje.

**Comment by ondrakoupil** [comment]
Zrovna u toho paymentOneClickStart se z $newPayment jen vezme payId. 
Ale je pravda, že třeba metoda paymentOneClickInit() potřebuje taky celý Payment objekt. Ale to je de facto ekvivalent k payment/init, je to první metoda, kterou budete volat, a ty následující už Payment nepotřebují anebo z něj berou jen PayID.
ApplePay metody v Client třídě implementované nejsou, ty je potřeba volat manuálně prostřednictvím metody customRequest.

**Comment by burrak** [comment]
Jasný, metody pro Apple Pay jsem si naimplementoval sám, ale i tak nedává smysl, že metoda `getPayId()` vrací `foreignId` property.
