### ISSUE TITLE
Pomoc s nastavením

### ISSUE THREAD

**Issue by NeXxik91** [ondrakoupil/csob#32]
Ahoj Ondro, rád bych zkusil využít tvoje řešení, ale nějak mi to hází chybu z SSL.

Includnul jsem classu, vytvořil php file, kde chci zkusit se přopojit s následujícím:

namespace OndraKoupil\Csob;
require( "config.php" );

$config = new Config(
	"XXX",
	"testy/keys/rsa_XXX.key",
	"testy/keys/mips_iplatebnibrana.csob.cz.pub",
	"Margareta Eshop",
        "https://www.my-eshop.cz/return-path.php",
         GatewayUrl::TEST_LATEST
);

$client = new Client($config);

try {
	$client->testGetConnection();
	$client->testPostConnection();

} catch (Exception $e) {
	echo "Something went wrong: " . $e->getMessage();
}

A hodí mi toto: 

Warning: openssl_verify(): supplied key param cannot be coerced into a public key in 
/classes/csob-client.php on line 2706

Warning: openssl_free_key() expects parameter 1 to be resource, bool given in 
/classes/csob-client.php on line 2707
Something went wrong: Result signature is incorrect. Please make sure that bank's public key in file specified in config is correct and up-to-date.

Přitom jsem si ale stáhnul oficiální klíč banky z jejich GITU. Nevíš čím to mohlo být? Díky za pomoc.

**Comment by NeXxik91** [comment]
Aha, tak už Vím čím to je, když jsem stáhnul aktuální testovací klíč banky z jejich gitu tak to nejde, jakmile jsem tam dal tvůj z testů, tak to šlape.

**Comment by ondrakoupil** [comment]
Prima, takže zavírám.
