### ISSUE TITLE
Missing hash method in Extension

### ISSUE THREAD

**Issue by toma10** [ondrakoupil/csob#34]
Po přechodu na verzi 1.8 jsme začali mít problém s použitím CardNumberExtension.

Pokud vypneme strict signature verification, tak vše projde v pořádku.

Nechybí ve třídě Extension na řádku 168 a 216 čtvrtý parametr hash method ($config->getHashMethod()) pro funkci Crypto::signString, respektive Crypto::verifySignature?

Díky za odpověď

**Comment by ondrakoupil** [comment]
Zkuste 8dd9639, mělo by to být v pořádku.

**Comment by rootpd** [comment]
Ahoj. Dnes som na tento problem narazil aj u nas a po chvilu som sa dopatral, ze si ho uz opravil. Myslis, ze by si ten commit mohol aj otagovat ako dalsiu verziu?

**Comment by rootpd** [comment]
Btw. mozem potvrdit, ze voci verzii v mastri overovanie podpisu extensiony funguje korektne.

**Comment by ondrakoupil** [comment]
@rootpd Zkuste v1.8.5

**Comment by rootpd** [comment]
@ondrakoupil Diky moc, to bolo rychle :). Idem na to.
