### ISSUE TITLE
ČSOB výměna API klíče 24.9.2021 ?

### ISSUE THREAD

**Issue by ETNyx** [ondrakoupil/csob#35]
Ahoj,

přišla notifikace o výměně klíčů v API u ČSOB. Moc z toho nejsem moudrý co se tam přesně děje. Je potřeba v implementaci nahrávat nějaký nový klíče?

Díky

**Comment by l1zard** [comment]
@ETNyx 

Pokud nepoužíváš ověření serveru platební brány (tento plugin to nemá ani implementováno), tak se to řešit nemusí. Není potřeba generovat ani nové klíče.

**Comment by ondrakoupil** [comment]
@ETNyx 

jde o HTTPS certifikát, ne o privátní klíč pro výpočet signatur. Záleží tedy na tom, zda na své straně ověřujete správnost certifikátu vzdáleného serveru při HTTPS spojení, anebo ne.

Jinými slovy - jde o proměnnou `Config->sslCertificatePath` v knihovně. Ta je defaultně prázdná a knihovna certifikát neověřuje. Takže pokud jste s tím nic nedělali, tak není třeba cokoliv řešit. 

Pokud jste si v rámci zvýšení zabezpečení stáhli k sobě certifikát od banky a nastavili při inicializaci `Config` objektu, tak bude potřeba certifikát vyměnit za ten nový, který banka má zveřejněný v tom článku. Po výměně pak doporučuji ověřit, že spojení funguje, stačí ručně přes Client->testGetConnection() nebo testPostConnection() - pokud tato volání API projdou, tak pak projdou všechna ostatní.

**Comment by ETNyx** [comment]
Super, díky za odpovědi.
