### ISSUE TITLE
platba na míru

### ISSUE THREAD

**Issue by ZdenekKrcal** [ondrakoupil/csob#36]
Ahoj,

děkuji za super plugin pro platební bránu. Klasické platby fungují parádně, jen mám problém se službou "platba na míru" kde je to v podstatě volání stejného požadavku payment/init ale s parametrem payOperation: customPayment (defaultně je payment). 

https://github.com/csob/paymentgateway/wiki/Platba-na-m%C3%ADru

https://github.com/csob/paymentgateway/wiki/Z%C3%A1kladn%C3%AD-metody#payment-init-operation

A právě když změním ten parametr tak požadavek selže a dostanu hlášku:

Result signature is incorrect. Please make sure that bank's public key in file specified in config is correct and up-to-date.

Mohl by si mi prosím poradit kde by mohl být problém?

Děkuji.

**Comment by ZdenekKrcal** [comment]
už jsem to vyřešil. Problém byl jinde.

**Comment by ondrakoupil** [comment]
Prima, díky.
