### ISSUE TITLE
InvalidSignature odpovědi v testovacím prostředí

### ISSUE THREAD

**Issue by Creeperface01** [ondrakoupil/csob#38]
Používám API 1.8 a v configu jsem nastavil svůj testovací privátní klíč a testovací veřejný klíč banky. Test připojení proběhne v pohodě a normálně se dostanu na platební bránu. Když pak ale jdu z brány zpět na web pro ověření platby tak `verifyResponseSignature` vrátí false. Tak teď moc nevím co je špatně

odpoveď z brány:
![image](https://user-images.githubusercontent.com/10363500/181713359-d559c331-6583-4a89-9209-c1d37d8c264f.png)

**Comment by ondrakoupil** [comment]
Zkuste prosím v knihovně aktivovat logování (https://github.com/ondrakoupil/csob#logován%C3%AD) a přiložit, co najdete v logu… třeba tam bude něco užitečného, co nás navede blíž.

**Comment by janbrasna** [comment]
@Creeperface01 Mozna za to mohou ta prazdna merchantData (base64 payload), zkuste si je neposilat tj. je nedostavat nazpet, pak mozna ten podpis bude sedet?
