### ISSUE TITLE
Support php 8.1

### ISSUE THREAD

**Issue by jAKErCZ** [ondrakoupil/csob#41]
Zdravím,
našel jsem chybku při vytváření platby na php 8.1 a to

`preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated`

řešení je:

`return preg_replace('~<br\s*/?>~i', "\n", $input ?: '');`
V Souboru Strings.php řádek 162.

Bylo by možné integrovat do stávajícího balíčku?

**Comment by ondrakoupil** [comment]
Dík za upozornění, zkuste aktuální [7e415db](https://github.com/ondrakoupil/csob/commit/7e415db42d541a5d66b6806c346c4b9ad4f02477), už by to mělo být v pořádku...
