### ISSUE TITLE
Error handling of Client requests

### ISSUE THREAD

**Issue by rootpd** [ondrakoupil/csob#43]
When CSOB returns `400 Bad request` in the API call, it also sends nice JSON error objects with the message what is wrong, for example:

```json
{"resultCode":110,"resultMessage":"Invalid format of name parameter, begins/ends with whitespace"}
```
However client for every `400` response returns the same message: "_Probably wrong signature, check crypto keys._" message. 

Would it be possible to:

- Check if the CSOB response is a valid JSON, and
- Extract the `message` property into the Exception message?

It would be a huge help when debugging failed requests on production environments.

Thanks.

**Comment by ondrakoupil** [comment]
Thanks, in new version 1.9.3 it will be handled better.

**Comment by janbrasna** [comment]
Since eAPI v1.9 all HTTP 400s basically mean value/validation errors, while signature related issues are 401s and key/merchant or timestamp woes are returned as 403s.
