### ISSUE TITLE
Shortended customer name shouldn't end with whitespace

### ISSUE THREAD

**Issue by markoph** [ondrakoupil/csob#44]
Hi,

[`OndraKoupil\Csob\Metadata\Customer#L88`](
https://github.com/ondrakoupil/csob/blob/2a82118ca1db334cc4ac4c044a756776b5677dfa/src/Metadata/Customer.php#L88) shortens customer's name to 45 characters:

```php
name' => Strings::shorten(trim($this->name), 45, '', true, true),
```

We had customer who put whole name into first name and company into surname. After shortening, last character was space. Eg.

- Before shortening
  `Alexander Random-Example-Surname - MyCompany Example Random`
- After (there is space in the end)
  `Alexander Random-Example-Surname - MyCompany `

API returned error (after digging & debugging; see related #43):

```json
{"resultCode":110,"resultMessage":"Invalid format of name parameter, begins/ends with whitespace"}
```

Maybe you'll could trim name also after shortening it.

```diff
-name' => Strings::shorten(trim($this->name), 45, '', true, true),
+name' => trim(Strings::shorten(trim($this->name), 45, '', true, true)),
```

We fixed our code to shorten name before setting it to the payment - so this is not a blocker for us. Just letting you know in case it affects others _(probability of such long name is small; feel free to close the ticket)_.

**Comment by ondrakoupil** [comment]
Thanks, new version 1.9.3 will handle this correctly.
