### ISSUE TITLE
Problem with currency

### ISSUE THREAD

**Issue by jaroslavmano** [ondrakoupil/csob#47]
Dobrý den,
při zadávání platby nastavím currency="EUR";  a po odeslání payment/init se mi zobrazí stránka s errorem: 
`Fatal error: Uncaught OndraKoupil\Csob\Exception: API returned an error: resultCode "110", resultMessage: Invalid currency in ...`

Přitom když se podívám do POSMerchantu (zkušebního), tak tam danou transakci vidím i ve správné měně, ale já se nedostanu ani k přesměrování na platební bránu i v logu se vypisuje správná měna "totalAmount":1800,"currency":"EUR" . Jedná se o API V1.9 .

Mohu tedy poprosit o radu?

**Comment by rootpd** [comment]
@jaroslvmano Vies tu prosim dat idealne cely payload aj odpoved, ktora z API prisla? Odpoved podla mna najdeme tam. Zapni si logovanie podla https://github.com/ondrakoupil/csob#logov%C3%A1n%C3%AD a nasledne sem posli, ze co ti pre takuto platbu zalogovalo.

**Comment by jaroslavmano** [comment]
Zde přikládám logy i celou chybovou hlášku a bohužel celý payload nejsem schopen dodat, jelikož se to plní daty z db. V případě kdy ale místo EUR je CZK, tak platba v pořádku projde.
![9AAD2D39-4CA4-4270-82E8-4CC2926BF2B6](https://user-images.githubusercontent.com/86402091/204275845-145b833d-ae4f-4edf-bb21-1f47b69050b2.jpeg)

[csob_log.txt](https://github.com/ondrakoupil/csob/files/10103592/csob_log.txt)
[csob_tracelog.txt](https://github.com/ondrakoupil/csob/files/10103593/csob_tracelog.txt)

**Comment by rootpd** [comment]
Vyzera, ze u mna sa to sprava voci testovaciemu prostrediu rovnako (skusal som aj API 1.8 aj 1.9). Ak si mam tipnut, tak to bude bud nastavenim merchanta na testovacom prostredi (v sprave CSOB), alebo ma nejaky problem samotne testovacie prostredie.

Kniznica tu robi vsetko dobre - podla logu odide do banky naozaj `EUR` a to je jedna z povolenych hodnot (vid [dokumentaciu](https://github.com/csob/paymentgateway/wiki/Basic-methods#paymentinit-method-)). Cize odporucam napisat do https://github.com/csob/paymentgateway alebo na kontakt v ramci CSOB, ktory mas k dispozicii, nech sa na to pozru. Pamatam si, ze nam specialne pre testovacie prostredie museli povolovat One click platby, mozno musia specialne povolit aj platbu v `EUR`.

**Comment by jaroslavmano** [comment]
Dobře děkuji za radu, jdu jim napsat a uvidím co mi odpoví.

**Comment by janbrasna** [comment]
EUR neni defaultne povolene (=reflektuje to chovani i produkce; EUR je potreba si smluvne vyzadat, tj. misto anonymniho ID uz mit finalni merchantId a pro nej si EUR nechat zapnout i na sandboxu), ale ta chybova hlaska neni zrovna navodna:/ Zjistuju v @csob zda ji neni mozne vylepsit, aby byl duvod zamitnuti hned jasnejsi.
