### ISSUE TITLE
Distribution folder in package

### ISSUE THREAD

**Issue by Pheat** [ondrakoupil/csob#49]
Zdravím,

je nutné mít ten zkompilovaný PHP soubor, který je v distu také v balíčku pro composer? Ne, že by to úplně dělalo problémy, jenom PHP storm nedetekuje psr-4 v composer.json ve vendoru v tom balíku a myslí si tedy, že například classa Config je definovaná vícekrát pod stejným namespacem. 
- jednou v dist zkompilovaném souboru
- podruhé v klasickém /src 

Tak buď nedávat vůbec dist do balíčku. Nebo případně udělat jinačí namespace pro to? 

Není to úplně problém, jenom mě to tak napadlo pro zajímavost. :) 

Díky.

**Comment by ondrakoupil** [comment]
Zdravím,
díky za podnět, je to dobrý nápad. Zkuste nainstalovat aktuální dev-master (26992fdde), už by tam dist neměl být.

**Comment by Pheat** [comment]
Super, děkuji moc :-)
