### ISSUE TITLE
EET

### ISSUE THREAD

**Issue by rydercz** [ondrakoupil/csob#5]
Dobrý den,
plánujete integraci EET, které ČSOB nabízí https://github.com/csob/paymentgateway/wiki/Spou%C5%A1t%C4%9Bn%C3%AD-slu%C5%BEby-EET ?
díky za info

**Comment by kockodev** [comment]
@ondrakoupil 
bez vysvětlení zavřít issue .. to není hezké :-1:

**Comment by ondrakoupil** [comment]
@rapemer protože zmiňované funkce jsou již implementované ve verzi v1.7, viz https://github.com/ondrakoupil/csob#eet
