### ISSUE TITLE
Wrong default value for language property

### ISSUE THREAD

**Issue by walja** [ondrakoupil/csob#50]
Zdravím, 
všiml jsem si drobné chyby ve třídě Payment, kde je pro $language nastavována výchozí hodnota "CZ"
`if (!$this->language) {
			$this->language = "CZ";
		}`
V dokumentaci je ale už uvedena hodnota "cs", viz. povolené hodnoty na jejich wiki:
https://github.com/csob/paymentgateway/wiki/Basic-Methods#paymentinit-method-

**Comment by ondrakoupil** [comment]
Díky za upozornění, vyřešeno ve v1.9.5 a v 3dfc715
