### ISSUE TITLE
chyba při instalaci přes composer

### ISSUE THREAD

**Issue by Trojda** [ondrakoupil/csob#51]
Při pokusu o instalaci přes "composer require ondrakoupil/csob-eapi-paygate" to padá na "Install of ondrakoupil/tools", viz

Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading ondrakoupil/tools (v1.2.4)
  - Downloading ondrakoupil/csob-eapi-paygate (v1.9.5)
  - Installing ondrakoupil/tools (v1.2.4): Extracting archive
    Install of ondrakoupil/tools failed
  - Installing ondrakoupil/csob-eapi-paygate (v1.9.5): Extracting archive
 1/1 [============================] 100%
In ZipDownloader.php line 223:
  The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArchive::extractTo(): Not a directory

In ZipDownloader.php line 210:
  ZipArchive::extractTo(): Not a directory

**Comment by jspetrak** [comment]
Did not happen to me today.

**Comment by ondrakoupil** [comment]
This should be fixed in new versions of dependency ondrakoupil/tools
