### ISSUE TITLE
Result signature is incorrect. Please make sure that bank's public key in file specified in config is correct and up-to-date.

### ISSUE THREAD

**Issue by hojgr** [ondrakoupil/csob#6]
Dobry den,

snazim se zprovoznit platebni branu avsak narazil jsem na tuto chybu:

Something went wrong: Result signature is incorrect. Please make sure that bank's public key in file specified in config is correct and up-to-date.

Vytvoril jsem si sandbox ID (https://iplatebnibrana.csob.cz/keygen/), stahnul private i public key, napsal spravne cestu k souborum a odeslal public key pomoci tlacitka po vygenerovani.

Zkusil jsem to nekolikrat - vzdy stejny problem.

Jak muzu tento problem vyresit?

Dekuji
Michal Hojgr

**Comment by kockodev** [comment]
@hojgr doporučil bych prozkoumat oficiální dokumentaci: https://github.com/csob/paymentgateway/wiki

**Comment by GEp1c** [comment]
Ten stejný problém právě dnes.

**Comment by hojgr** [comment]
@GEp1c Zapomnel jsem sem napsat řešení.

Den na to jsem našel řešení v příkladech v repo.

Z dokumentace to není úplně jasné, ale musí se použit VLASTNÍ SOUKROMÝ KLÍČ a VEŘEJNÝ KLÍČ BANKY. Nikoli vlastni soukromý i veřejný klíč.
