### ISSUE TITLE
currency issue

### ISSUE THREAD

**Issue by lamvanduyet** [ondrakoupil/csob#8]
Is it possible to change currency in CSOB gateway and EET extension? I would like to change from CZK to EUR and vice versa. Thank you for answer.

**Comment by ondrakoupil** [comment]
Sure. Just set $currency in Payment object:
`$payment->currency = "EUR";`
I am not sure if you need some kind of special permission from CSOB to use foreign currencies in production environment. In testing environment it works, though.

**Comment by lamvanduyet** [comment]
thanks for answer
