### ISSUE TITLE
addCartItem can add invalid description

### ISSUE THREAD

**Issue by wentylos** [ondrakoupil/csob#9]
Since parameter description in addCartItem is limited to 40 character, there should be fifth parameter in call Strings::shorten set to true, so as the shorten method would not producer longer strings then 40 character. See Payment::addCartItem. 

Now i tries not to split the text if the 40-th character is in the middle of the word. It leads to possibility to producer longer string then 40 characters, that leads to API response with: API returned an error: resultCode "110", resultMessage: Invalid length of cart/description parameter.

Parameter $name seems not to face same behaviour, since its shorten call contains 5-th parameter set to true.

Hope it's one line fix.

**Comment by ondrakoupil** [comment]
Hi,
thanks. it is fixed in new release v1.7.3
